services:
  api:
    build: .
    command: uvicorn app.services.api:app --host 0.0.0.0 --port 8000
    env_file: .env
    volumes: [".:/app"]
    ports: ["8000:8000"]
  ui:
    build: .
    command: streamlit run ui/streamlit_app.py --server.port 8501
    env_file: .env
    volumes: [".:/app"]
    ports: ["8501:8501"]
  prometheus:
    image: prom/prometheus:latest
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml"]
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]
    volumes: ["./grafana:/var/lib/grafana"]


