name: build-sign
on:
  push:
    branches: [ feat/platform-hardening ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/perception-lab:${{ github.sha }} .
      - name: Install syft/grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Generate SBOM
        run: |
          syft packages dir:. -o spdx-json > artifacts-sbom.spdx.json
      - name: Scan image
        run: |
          grype ghcr.io/${{ github.repository }}/perception-lab:${{ github.sha }} --fail-on Critical || (echo "Critical vulns found" && exit 1)
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.7.0
      - name: Sign image
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign sign -y ghcr.io/${{ github.repository }}/perception-lab:${{ github.sha }}

